name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # jab bhi tum main branch pe push karoge, build hoga

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Code checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: DockerHub login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: paras910/springboot-app:latest
